export * from './teams.interface';
export * from './pages.interface';
export * from './datocms.interface';
export * from './image.interface';
export * from './products.interface';
export * from './managers.interface';
export * from './categories.interface';
export * from './partners.interface';
export * from './tags.interface';